Name:           ros-melodic-moveit-visual-tools
Version:        3.2.1
Release:        3%{?dist}
Summary:        ROS moveit_visual_tools package

Group:          Development/Libraries
License:        BSD
URL:            https://github.com/davetcoleman/moveit_visual_tools
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-cmake-modules
Requires:       ros-melodic-eigen-conversions
Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-graph-msgs
Requires:       ros-melodic-moveit-core
Requires:       ros-melodic-moveit-ros-robot-interaction
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-roslint
Requires:       ros-melodic-rviz-visual-tools
Requires:       ros-melodic-std-msgs
Requires:       ros-melodic-tf-conversions
Requires:       ros-melodic-trajectory-msgs
Requires:       ros-melodic-visualization-msgs
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-cmake-modules
BuildRequires:  ros-melodic-eigen-conversions
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-graph-msgs
BuildRequires:  ros-melodic-moveit-core
BuildRequires:  ros-melodic-moveit-ros-robot-interaction
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-roslint
BuildRequires:  ros-melodic-rviz-visual-tools
BuildRequires:  ros-melodic-std-msgs
BuildRequires:  ros-melodic-tf-conversions
BuildRequires:  ros-melodic-trajectory-msgs
BuildRequires:  ros-melodic-visualization-msgs

%description
Helper functions for displaying and debugging MoveIt! data in Rviz via published
markers

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Wed Sep 05 2018 Dave Coleman <davetcoleman@gmail.com> - 3.2.1-3
- Autogenerated by Bloom

* Fri Jun 08 2018 Dave Coleman <davetcoleman@gmail.com> - 3.2.1-2
- Autogenerated by Bloom

* Fri Jun 08 2018 Dave Coleman <davetcoleman@gmail.com> - 3.2.1-1
- Autogenerated by Bloom

* Thu May 31 2018 Dave Coleman <davetcoleman@gmail.com> - 3.2.1-0
- Autogenerated by Bloom

